CREATE TABLE IF NOT EXISTS public.progresso_historia (
  id_progresso_historia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL,
  id_modulo INTEGER NOT NULL,
  concluido BOOLEAN NOT NULL DEFAULT FALSE,
  concluido_em TIMESTAMPTZ,

  CONSTRAINT fk_progresso_historia_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario)
    ON DELETE CASCADE,

  CONSTRAINT fk_progresso_historia_modulo
    FOREIGN KEY (id_modulo)
    REFERENCES public.modulos (id_modulo)
    ON DELETE CASCADE,

  CONSTRAINT uq_progresso_historia_usuario_modulo
    UNIQUE (id_usuario, id_modulo)
);

CREATE TABLE IF NOT EXISTS public.progresso_desafio (
  id_progresso_desafio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL UNIQUE,
  modulo_desafio_atual INTEGER NOT NULL DEFAULT 1,
  falhas_no_modulo INTEGER NOT NULL DEFAULT 0,
  certificado_liberado BOOLEAN NOT NULL DEFAULT FALSE,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_progresso_desafio_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario)
    ON DELETE CASCADE
);

INSERT INTO public.progresso_desafio (
  id_usuario,
  modulo_desafio_atual,
  falhas_no_modulo,
  certificado_liberado
)
SELECT
  u.id_usuario,
  1,
  0,
  false
FROM public.usuarios AS u
ON CONFLICT (id_usuario)
DO NOTHING;
